### ISSUE TITLE
Remove the one day ban

### ISSUE THREAD

**Issue by CylindricAnt606** [venkateshdudyala/anonymous_sms#1]
i like this project but I HATE THE ONE DAY QUOTA REMOVE NOW PLZZZZZZZZ

**Comment by MR-ROGUE** [comment]
Any issues raised by this tool is solely responsible by the end user, The message limit is set only for preventing misusing of this tool kindly note this that's all, thank you.
If you like this tool A star to this project'ld be grateful, thank you.
